### ISSUE TITLE
More... page needs updating

### ISSUE THREAD

**Issue by chrisretusn** [arantius/resurrect-pages#10]
The "More" page from Add-ons Manager is out of date. Still shows CoralCDN, Yahoo, Bing, Gigablast. 

"... please file a ticket: http://trac.arantius.com/wiki/Tickets" should probably be updated. I does redirect to github, but may confuse users. Same goes for Homepage.

Nice extension btw, be using it for a while.

**Comment by arantius** [comment]
I think this all comes from AMO, so should be fixed once various caches expire.  (Because I edited it online ...)

**Comment by chrisretusn** [comment]
Makes sense. Thanks.

**Comment by arantius** [comment]
Looks updated for me today, thanks for the report.
