### ISSUE TITLE
"Report this error" broken

### ISSUE THREAD

**Issue by flyingzebras** [arantius/resurrect-pages#15]
The link "Report this error" is dead, can you please fix it?

Using IceCat 38.3.0 (package icecat in Trisquel 7) based on Firefox ESR 38.3.0.

**Comment by arantius** [comment]
I don't know what you're talking about and I don't believe it to be related to this tool.

**Comment by flyingzebras** [comment]
@arantius I meant that the link "Report this error", see https://support.cdn.mozilla.net/media/uploads/gallery/images/2015-04-15-14-39-26-27afc3.png, is missing. Can you please add it?

**Comment by arantius** [comment]
Missing when, how?  What does this have to do with Resurrect Pages?

**Comment by flyingzebras** [comment]
@arantius I thought that RP substituted the default page.

**Comment by arantius** [comment]
No.  Appends to it.

**Comment by flyingzebras** [comment]
@arantius I confirmed that you are right. Sorry.
