### ISSUE TITLE
Feature request: Have two Archive.org options

### ISSUE THREAD

**Issue by trlkly** [arantius/resurrect-pages#16]
With some pages, having a direct link to the latest version of the page on archive.org will result in a redirection to another page. This makes it very difficult to go back to an earlier version.

It would be really nice to add an additional option. Have one button be "The Internet Archive (latest)" and the other be "The Internet Archive (all)". OR maybe "The Internet Archive (list)."

**Comment by arantius** [comment]
This sounds reasonable.
