### ISSUE TITLE
Wrong keyboard shortcut

### ISSUE THREAD

**Issue by danilococcia** [arantius/resurrect-pages#18]
The keyboard shortcut ctrl+shift+U is not working.
I discovered it trying to the change tabs group, by using the Ctrl+shift+E shortcut, that now actually brings up this plugin.
The ctrl+shift+U does nothing at all!

**Comment by arantius** [comment]
Works for me (both -U and -E).  What platform are you on?

**Comment by danilococcia** [comment]
Firefox 44.0 on Win7 and Win10.
The behaviour changed after I installed the "Tab Groups" plugin, to
substitute the now gone Firefox functionality.
I have right now made a check disabling the plugin: when the plugin is
disabled the shortcut works :(
I'll notify the other plugin author of the problem.
Sorry for the noise.

2016-02-04 22:21 GMT+01:00 arantius <notifications@github.com>:

**Comment by arantius** [comment]
I also have Tab Groups installed, though I haven't checked on Windows.  But this seems to be working as intended.
