### ISSUE TITLE
Archive.is is broken?

### ISSUE THREAD

**Issue by sergeevabc** [arantius/resurrect-pages#23]
Dear @arantius, it seems Archive is not available via HTTPS since browser outputs “Secure connection failed”, however usual HTTP connection works fine. So what should we do?

**Comment by Albirew** [comment]
I currently bump into a cloudflare captcha page for archive.is so it seems like they have (had?) problems on their side. Nothing Arantius can do.

**Comment by arantius** [comment]
WFM now.  Temporary service issue unrelated to this extension.

**Comment by sergeevabc** [comment]
Try to open:
- https://archive.is/http://some404website.com/ does not work, [proof](https://ukaz.cz/a/1478185646_138581b52ae2a2cd.png)
- http://archive.is/http://some404website.com/ works

**Comment by arantius** [comment]
Both work for me, your browser must be misconfigured.

**Comment by sergeevabc** [comment]
Oh, it turned out that Archive.is served via HTTPS is blocked in Russia.
Reason is that a couple of mirrors spread information about illegal drugs.
Alas, local authorities fulfill a court order by means of restricting access to IP.
Good news: Archive.is could be reached via HTTP for now, because is hosted on different IP.
