### ISSUE TITLE
Server Not Found Broken Page Layout

### ISSUE THREAD

**Issue by SimpleUser123** [arantius/resurrect-pages#24]
Hello,

I am running this extension in the latest Firefox 50, and the new 404 page is ugly and your extension pushes it partially off the page.
Is there any way to fix this or just revert to the old 404 page??

I have attached a screenshot of my setup for your viewing pleasure.

Thanks!

![server not found 404 resurrection](https://cloud.githubusercontent.com/assets/24279838/20819748/d7d02738-b80c-11e6-9496-f860d878e2d0.PNG)

**Comment by Albirew** [comment]
these icons with a touch of gloss near start menu... is that... windows Me?

**Comment by arantius** [comment]
Turns out the default page has a hard coded number of pixels wide at which to hide the "i" icon, but the overlay makes it wider.  Confirmed that this happens, but it's a pretty small issue.
