### ISSUE TITLE
Incompatible with multiprocess Firefox?

### ISSUE THREAD

**Issue by aroskuski** [arantius/resurrect-pages#26]
The release notes for version 3.0 suggest that compatibility with multiprocess Firefox was added, but it seems to be reported as incompatible by the Add-on Compatibility Reporter.
![selection_176](https://cloud.githubusercontent.com/assets/5818314/22393367/0b2d3dd0-e4d3-11e6-973d-55f055c4ab73.png)

If it is actually compatible, it'd be good if the addon could be updated so that the manifest properly declares it compatible.
If not, would it be possible to add multiprocess compatibility?

**Comment by Changaco** [comment]
I also use this extension and I've recently force-enabled multiprocessing on my Firefox, no crash so far.

**Comment by arantius** [comment]
With WebExtensions looming to break everything, I'm planning no invested effort in Firefox extensions, besides maybe working once that happens.

**Comment by DaAwesomeP** [comment]
@arantius I think that this extension could be mostly moved over to WebExtensions with little API trouble. The only thing I think that will have to be dropped will be the menu on the `Server Not Found` page.

**Comment by sputnik1** [comment]
If you can possibly spare the time, please convert Resurrect Pages to WebExtensions. Many like myself have used your add-on for years and would greatly appreciate your effort. Thank you.

**Comment by girst** [comment]
I've submitted a [pull request](https://github.com/arantius/resurrect-pages/pull/27) that rewrites this extension as a webextension. it is a bit different (no popup window anymore, but a nested context menu).

I've never written a webextension before, so I'd appreciate some feedback and maybe some help
