### ISSUE TITLE
WebExt for FF versions <57

### ISSUE THREAD

**Issue by Rick-74** [arantius/resurrect-pages#29]
Hi,
I see that a new WebExtension version of this (quite useful) addon has been uploaded on AMO, but it seems to be compatible only with FF >57, thus unistallable on the current stable (or beta). 
Could it be possibile to lower the min version requirement to make it possible for people to upgrade right away (and be ready for a smooth transition in November), or is the new version of the addon using APIs only present on 57+ (if that's the case, sorry for the noise)?

**Comment by yfdyh000** [comment]
https://addons.mozilla.org/firefox/addon/archiver-menu/

**Comment by TheDcoder** [comment]
Try older versions of the addon: https://addons.mozilla.org/en-GB/firefox/addon/resurrect-pages/versions/

**Comment by davidhedlund** [comment]
Resurrect Pages version 5 is broken for 57.0.4:
* There is no context menu.
* The add-on bar icon popup options (with Google, with Google (text only), with The Internet Archive, etc) doesn't work either.
