### ISSUE TITLE
Latest version 2.0.7 is only compatible with firefox version 3.0 to 5.*

### ISSUE THREAD

**Issue by rajivbandi** [arantius/resurrect-pages#3]
The latest version (2.0.7) is compatible till firefox 5.* . Hence it does not show up in the latest version in firefox addons. 2.0.6 is only shown as the latest version.
I found this in the install.rdf 
<em:minVersion>3.0</em:minVersion>
<em:maxVersion>5.*</em:maxVersion>

I think max version should be 25.*
Thank you

**Comment by arantius** [comment]
AMO manages this long term.  I'll update the version numbers as part of a release with actual changes, but I'm not going to packages releases just to bump these numbers.
