### ISSUE TITLE
New WebExt version remains impossible to install from AMO in Firefox Nightly 57.0a1 (2017-08-31)

### ISSUE THREAD

**Issue by ronjouch** [arantius/resurrect-pages#30]
In the [AMO page](https://addons.mozilla.org/en-US/firefox/addon/resurrect-pages/), the addon seems installable: `Add to Firefox` button is green. But when clicking it, I get a `Resurrect Pages could not be installed because it is not compatible with Nightly 57.0a1`.

Am I doing anything wrong?

**Comment by arantius** [comment]
Mozilla is arbitrarily strict about which minimum versions you can put, so expected.

**Comment by ronjouch** [comment]
> *Mozilla is arbitrarily strict about which minimum versions you can put, so expected.*

@arantius thanks for the prompt answer and no problem with the closing, but I don't understand what you mean, could you detail? When will it be installable? In which Firefox version?
