### ISSUE TITLE
unsigned

### ISSUE THREAD

**Issue by Tleilax-BTHQ** [arantius/resurrect-pages#37]
Your extension is unsigned. Today, it is blocked in Firefox 62.0. Can you get it signed?

**Comment by arantius** [comment]
I don't know what you mean, it's hosted on AMO, which does the signing:

https://addons.mozilla.org/en-US/firefox/addon/resurrect-pages/

**Comment by arantius** [comment]
(And I'm currently using it, in FF 62.)

**Comment by Tleilax-BTHQ** [comment]
You are right. I did have a problem. After updating your extension, it
worked again. An, yours wasn't the only one. It must be a problem with my
profile. Sorry to have bothered you!

Thanks for helping me 😀

Carl
