### ISSUE TITLE
Overlay broken links on websites

### ISSUE THREAD

**Issue by allopislozano** [arantius/resurrect-pages#38]
Hi there! Awesome firefox plugin. One feature suggestion:

I sometimes browse websites that are quite old and most of the links are broken. It would be very nice if the links could show that information up front, and ideally also only show the caches that contain related information (not always all of them)

Anyways , just as a suggestion. 

Thanks, awesome plugin

**Comment by arantius** [comment]
It would have to try to fetch every single thing ever linked to, to know if the link is broken or not.  No plans to do that.  (Same for which is available: it would require hitting every site, which I don't want to do.)
