### ISSUE TITLE
Feature request: disable Ctrl+Shift+U

### ISSUE THREAD

**Issue by GKFX** [arantius/resurrect-pages#4]
[Someone in the comments](https://addons.mozilla.org/en-us/firefox/addon/resurrect-pages/reviews/645742/) said:
>By chance I found out [ctrl sh U] runs it. We should better have a menu to make our choice or just disable it. Thanks for working on it ASAP

**Comment by arantius** [comment]
I see no evidence that it's hurting anything, so no reason to remove it.
