### ISSUE TITLE
strict_min_version (compatibility with Waterfox Classic)

### ISSUE THREAD

**Issue by grahamperrin** [arantius/resurrect-pages#45]
At a glance, version 7 appears to work with Waterfox Classic 2019.12. 

Should I be aware of any incompatibility? 

tl;dr historically, Waterfox 56 was based on Firefox 56.0.2.

**Comment by arantius** [comment]
I will never test on, so won't claim compatibility with, anything but Firefox.

**Comment by grahamperrin** [comment]
OK, thanks. 

> Should I be aware of any incompatibility?

If I find any, I'll add a post-closure comment.
