### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by selvmaya** [arantius/resurrect-pages#50]
Last issue with a reply was in 2020, and the latest commit was 4 years ago. I want to try this extension, and am interested in why this repository seems to be so inactive.

**Comment by arantius** [comment]
Because it works.  What's to "maintain"?  It doesn't need to change.

**Comment by selvmaya** [comment]
Maintaining (as I understand the word) isn't necessarily about changing anything. Making sure it works is enough!
I guess I should have asked if it still fully worked?
I would generally expect that older plugins tend to break when used in newer versions of their host app. Not here to complain of course, it's just rare to see untouched repositories reflect projects that still work in something continually changed and reworked like a browser.
(Btw this plugin is very useful, thanks for making it!)
